base_dir:
ga_id:
google_search_api_key:
google_search_site_url:
title_suffix: Adriaan Moors's homepage - 
# To add a new section:
#   bin/add_section.sh . section_name
# 
# To add a new post in a section:
#   bin/add_new_post.sh ./path/to/section title
# 
# If you host your website on Github Pages, you might be interested in the base_dir option in _config.yaml: just set it to 
#   base_dir: /project_name
